### ISSUE TITLE
Discussing rule: fp/no-mutating-methods

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/eslint-config-node#130]
I find myself skipping this rule whenever I need to sort an array. Take the following example:

```js
const applyConfigToFunction = ({ config, func }) => {
  // It's safe to mutate the array because it's local to this function.
  // eslint-disable-next-line fp/no-mutating-methods
  const matches = Object.keys(config)
    .filter((expression) => minimatch(func.name, expression))
    .map((expression) => {
      const starCount = [...expression].filter((char) => char === '*').length

      return {
        expression,
        weight: expression.length - starCount - (starCount ? 1 : 0),
      }
    })
    .sort((fA, fB) => fA.weight - fB.weight)
  const functionConfig = matches.reduce((result, { expression }) => mergeConfigObjects(result, config[expression]), {})

  return {
    [func.name]: functionConfig,
  }
}
```

In my view, this example adheres to the functional programming paradigm. The usage of `sort` does not cause any side effects. More importantly, there are no obvious alternatives to it.

What do you think?

**Comment by ehmicky** [comment]
`Array.sort()` mutates the array, but in the case above the array is shallow cloned by both `Array.filter()` and `Array.map()`. In some situations, `Array.slice().sort()` can also be used to prevent mutating the array.

Using an utility method like [here](https://github.com/ehmicky/autoserver/blob/a8ca12ffb9b63193a52027bb0f2004d5fdda5ebf/src/utils/functional/sort.js#L3-L7) could help, but I agree this is verbose. :/

**Comment by eduardoboucas** [comment]
Closing due to #206.
